### ISSUE TITLE
Manage releases with goreleaser

### ISSUE THREAD

**Issue by roee88** [mesh-for-data/vault-plugin-secrets-kubernetes-reader#2]
It seems like plugins are usually released as binaries. 

GoReleaser can be used for that. See [.goreleaser.yml](https://github.com/mesh-for-data/openapi2crd/blob/main/.goreleaser.yml) and [release.yml](https://github.com/mesh-for-data/openapi2crd/blob/main/.github/workflows/release.yml) for an example usage.

You then don't really need to build a docker image because you can just pull the binary from your init container instead. However, if a docker image is desired then goreleaser can build and push those too.

**Comment by revit13** [comment]
Thanks @roee88 I'll have a look.
